197. Rising Temperature

In [2]:
print(1)

1

In [1]:
import pandas as pd

weather = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "recordDate": [
        "2015-01-02",
        "2015-01-01",
        "2015-01-03",
        "2015-01-04"
    ],
    "temperature": [25, 10, 20, 30]
})

print(weather)

   id  recordDate  temperature
0   1  2015-01-02           25
1   2  2015-01-01           10
2   3  2015-01-03           20
3   4  2015-01-04           30

In [2]:
weather.sort_values('recordDate',inplace= True)
weather

   id  recordDate  temperature
1   2  2015-01-01           10
0   1  2015-01-02           25
2   3  2015-01-03           20
3   4  2015-01-04           30

In [5]:
weather['recordDate']  = pd.to_datetime(weather['recordDate'])
weather['next_day'] = weather['recordDate'] + pd.Timedelta(days=1)

In [10]:
merger = weather.merge(weather,left_on='next_day',right_on = 'recordDate')

In [18]:
merger[merger['temperature_x']<merger['temperature_y']][['id_y']].rename(columns = {'id_y':'id'})

   id
0   1
2   4